ARCHIVO_USUARIOS = 'usuarios.json'
ARCHIVO_PRODUCTOS = 'dataset_productos.csv'
ARCHIVO_CLIENTES = 'dataset_clientes.csv'
ARCHIVO_VENTAS = 'dataset_ventas.csv'
CODIFICACION = 'UTF-8'
ARCHIVO_DETALLE_VENTA = 'dataset_detalle_venta.csv'